package awshelpers

import (
	"fmt"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/service/ec2"
)

func GetInstanceID(message AlarmMessage) (response string, err error) {
	for _, Dimension := range message.Trigger.Dimensions {
		if Dimension.Name == "InstanceId" {
			return Dimension.Value, nil
		}
	}

	return "", fmt.Errorf("no InstanceID in Cloudwatch Alarm message")
}

func GetInstanceTag(instanceID string, tagName string, svc *ec2.EC2) (tag string, err error) {
	input := &ec2.DescribeTagsInput{
		Filters: []*ec2.Filter{
			{
				Name: aws.String("resource-id"),
				Values: []*string{
					aws.String(instanceID),
				},
			},
		},
	}

	result, err := svc.DescribeTags(input)

	for _, Tag := range result.Tags {
		if *Tag.Key == tagName {
			return *Tag.Value, nil
		}
	}

	return "", err
}

func GetInstanceASG(instanceID string, svc *ec2.EC2) (response string, err error) {
	if instanceID != "" {
		// Automatically generated by AWS if EC2 instance is associated with an ASG
		tag := "aws:autoscaling:groupName"
		response, err := GetInstanceTag(instanceID, tag, svc)

		if response == "" {
			return "", fmt.Errorf("auto scaling group not associated with this instance")
		}
		return response, err
	}

	return "", nil
}
